version: '3'

services:
  animeserverpg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'animeserverpg'
    restart: always
    volumes:
      - animeserverpg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  animeserverpg-data:
